"""initial_schema

Revision ID: 946d7df7c3bf
Revises: 
Create Date: 2026-05-18 09:54:20.985428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946d7df7c3bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('related_ids', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_alerts_detected_at'), 'anomaly_alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomaly_alerts_ticker'), 'anomaly_alerts', ['ticker'], unique=False)
    op.create_table('congress_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('member', sa.String(length=200), nullable=False),
    sa.Column('party', sa.String(length=1), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount_min', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_max', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('days_to_disclose', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_congress_trades_disclosed_at'), 'congress_trades', ['disclosed_at'], unique=False)
    op.create_index(op.f('ix_congress_trades_ticker'), 'congress_trades', ['ticker'], unique=False)
    op.create_table('darkpool_prints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('short_volume', sa.Integer(), nullable=False),
    sa.Column('short_exempt_volume', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Integer(), nullable=False),
    sa.Column('short_pct', sa.Float(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_darkpool_prints_report_date'), 'darkpool_prints', ['report_date'], unique=False)
    op.create_index(op.f('ix_darkpool_prints_ticker'), 'darkpool_prints', ['ticker'], unique=False)
    op.create_table('insider_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('insider_name', sa.String(length=200), nullable=False),
    sa.Column('insider_title', sa.String(length=200), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('form_url', sa.String(length=500), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_trades_filed_at'), 'insider_trades', ['filed_at'], unique=False)
    op.create_index(op.f('ix_insider_trades_ticker'), 'insider_trades', ['ticker'], unique=False)
    op.create_table('options_flow',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('call_put', sa.String(length=4), nullable=False),
    sa.Column('premium', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('vol_oi_ratio', sa.Float(), nullable=False),
    sa.Column('unusual_score', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_flow_detected_at'), 'options_flow', ['detected_at'], unique=False)
    op.create_index(op.f('ix_options_flow_ticker'), 'options_flow', ['ticker'], unique=False)
    op.create_index(op.f('ix_options_flow_unusual_score'), 'options_flow', ['unusual_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_flow_unusual_score'), table_name='options_flow')
    op.drop_index(op.f('ix_options_flow_ticker'), table_name='options_flow')
    op.drop_index(op.f('ix_options_flow_detected_at'), table_name='options_flow')
    op.drop_table('options_flow')
    op.drop_index(op.f('ix_insider_trades_ticker'), table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_filed_at'), table_name='insider_trades')
    op.drop_table('insider_trades')
    op.drop_index(op.f('ix_darkpool_prints_ticker'), table_name='darkpool_prints')
    op.drop_index(op.f('ix_darkpool_prints_report_date'), table_name='darkpool_prints')
    op.drop_table('darkpool_prints')
    op.drop_index(op.f('ix_congress_trades_ticker'), table_name='congress_trades')
    op.drop_index(op.f('ix_congress_trades_disclosed_at'), table_name='congress_trades')
    op.drop_table('congress_trades')
    op.drop_index(op.f('ix_anomaly_alerts_ticker'), table_name='anomaly_alerts')
    op.drop_index(op.f('ix_anomaly_alerts_detected_at'), table_name='anomaly_alerts')
    op.drop_table('anomaly_alerts')
    # ### end Alembic commands ###
